name: Convert CSV to JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use a personal access token with proper permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CSV to JSON Conversion
        run: |
          echo "Starting conversion..."
          node Json/CsvToJson.js > conversion.log 2>&1 || echo "⚠️ Script failed with exit code $?"
          cat conversion.log  # Show full logs

      - name: Debug JSON Output
        run: |
          echo "Checking JSON output..."
          ls -lah Json || echo "⚠️ No Json directory found"
          find Json -type f || echo "⚠️ No JSON files found"
          head -n 20 Json/*.json || echo "⚠️ JSON files exist but failed to read"

      - name: Commit and Push JSON Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # First fetch the latest changes
          git fetch origin
          
          # Remove old database files from Git tracking
          git rm -f Json/midi-database-*.json Json/midi-database-*.json.gz 2>/dev/null || echo "No old files to remove from Git"
          
          # Add the new files
          git add Json/*.json Json/*.json.gz || echo "⚠️ No files to stage"
          
          # Only proceed if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Create a commit
            git commit -m "Update MIDI JSON database"
            
            # Try to rebase first
            git pull --rebase origin main
            
            # Push with force if needed
            git push -f
          fi