name: Convert CSV to JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run CSV to JSON Conversion
        run: |
          echo "Starting conversion..."
          node csvtojson.js > conversion.log 2>&1 || echo "⚠️ Script failed with exit code $?"
          cat conversion.log  # Show full logs

      - name: Debug JSON Output
        run: |
          echo "Checking JSON output..."
          ls -lah Json || echo "⚠️ No Json directory found"
          find Json -type f || echo "⚠️ No JSON files found"
          head -n 20 Json/*.json || echo "⚠️ JSON files exist but failed to read"

      - name: Commit and Push JSON Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add Json/*.json Json/*.json.gz || echo "⚠️ No files to stage"
          git diff --staged --quiet || (git commit -m "Update MIDI JSON database" && git push)
