name: Convert CSV to JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CSV to JSON Conversion
        run: |
          echo "Starting conversion..."
          node Json/CsvToJson.js > conversion.log 2>&1 || echo "⚠️ Script failed with exit code $?"
          cat conversion.log  # Show full logs

      - name: Debug JSON Output
        run: |
          echo "Checking JSON output..."
          ls -lah Json || echo "⚠️ No Json directory found"
          find Json -type f || echo "⚠️ No JSON files found"
          head -n 20 Json/*.json || echo "⚠️ JSON files exist but failed to read"

      - name: Commit and Push JSON Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Ensure we have the latest changes
          git pull origin main --rebase
          
          # First remove any old database files from git's perspective
          git rm -f Json/midi-database-*.json Json/midi-database-*.json.gz 2>/dev/null || echo "No old files to remove from Git"
          
          # Add new files
          git add Json/*.json Json/*.json.gz || echo "⚠️ No files to stage"
          
          # Commit and push if there are changes
          git diff --staged --quiet || (git commit -m "Update MIDI JSON database" && git push)